default: &default
  adapter: postgresql
  encoding: utf8
  timeout: <%= ENV.fetch('BRLCAD_PG_TIMEOUT').to_i %>
  pool: <%= ENV.fetch('BRLCAD_PG_POOL').to_i %>
  port: <%= ENV.fetch('BRLCAD_PG_PORT').to_i %>
  host: <%= ENV.fetch('BRLCAD_PG_HOST') %>
  database: <%= ENV.fetch('BRLCAD_PG_DATABASE') %>
  username: <%= ENV.fetch('BRLCAD_PG_USERNAME') %>
  password: <%= ENV.fetch('BRLCAD_PG_PASSWORD') %>

development:
  <<: *default

test:
  <<: *default
  database: brl_cad_test

production:
  <<: *default
