default: &default
  adapter: postgresql
  encoding: utf8
  timeout: 5000
  pool: 5
  database: brl_cad_development
  username: postgres
  password: testing
  port: 5432
  host: 127.0.0.1

development:
  <<: *default

test:
  <<: *default
  database: brl_cad_test

production:
  <<: *default
  database: brl_cad_production
