---
:verbose: false
:pidfile: ./tmp/pids/sidekiq.pid
:concurrency: 6
:queues:
  - [high, 3]
  - [default, 2]
  - [low, 1]

:schedule:
  CadRateFinderScheduler:
    every: [ '15m', first_in: '1s']
    queue: high
