---
:verbose: <%= ENV.fetch('BRLCAD_SIDEKIQ_VERBOSE') %>
:pidfile: <%= ENV.fetch('BRLCAD_SIDEKIQ_PIDFILE') %>
:concurrency: <%= ENV.fetch('BRLCAD_SIDEKIQ_CONCURRENCY').to_i %>
:queues:
  - [high, 3]
  - [default, 2]
  - [low, 1]

:schedule:
  CadRateFinderScheduler:
    every: [ '15m', first_in: '1s']
    queue: high
