ExchangeHouse.create(name: 'CadRateFinder::Spmundi')
ExchangeHouse.create(name: 'CadRateFinder::Moneyexchangeworld')
ExchangeHouse.create(name: 'CadRateFinder::Kantor')
ExchangeHouse.create(name: 'CadRateFinder::Cambiobr')
ExchangeHouse.create(name: 'CadRateFinder::Akgcorretora')
ExchangeHouse.create(name: 'CadRateFinder::Cambionet')
ExchangeHouse.create(name: 'CadRateFinder::Lojamultimoney')
ExchangeHouse.create(name: 'CadRateFinder::Wallstreetfinance')
